// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jedi-knights/go-semantic-release/internal/ports (interfaces: GitRepository,CommitParser,ProjectDiscoverer,ProjectImpactAnalyzer,VersionCalculator,ChangelogGenerator,TagService,ReleasePublisher,ConfigProvider,FileSystem,TemplateRenderer,Logger,Clock,Plugin,VerifyConditionsPlugin,AnalyzeCommitsPlugin,VerifyReleasePlugin,GenerateNotesPlugin,PreparePlugin,PublishPlugin,AddChannelPlugin,SuccessPlugin,FailPlugin)
//
// Generated by this command:
//
//	mockgen -destination=internal/ports/mocks/mocks.go -package=mocks github.com/jedi-knights/go-semantic-release/internal/ports GitRepository,CommitParser,ProjectDiscoverer,ProjectImpactAnalyzer,VersionCalculator,ChangelogGenerator,TagService,ReleasePublisher,ConfigProvider,FileSystem,TemplateRenderer,Logger,Clock,Plugin,VerifyConditionsPlugin,AnalyzeCommitsPlugin,VerifyReleasePlugin,GenerateNotesPlugin,PreparePlugin,PublishPlugin,AddChannelPlugin,SuccessPlugin,FailPlugin
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fs "io/fs"
	reflect "reflect"
	time "time"

	domain "github.com/jedi-knights/go-semantic-release/internal/domain"
	ports "github.com/jedi-knights/go-semantic-release/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepository is a mock of GitRepository interface.
type MockGitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryMockRecorder is the mock recorder for MockGitRepository.
type MockGitRepositoryMockRecorder struct {
	mock *MockGitRepository
}

// NewMockGitRepository creates a new mock instance.
func NewMockGitRepository(ctrl *gomock.Controller) *MockGitRepository {
	mock := &MockGitRepository{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepository) EXPECT() *MockGitRepositoryMockRecorder {
	return m.recorder
}

// CommitsSince mocks base method.
func (m *MockGitRepository) CommitsSince(ctx context.Context, sinceHash string) ([]domain.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitsSince", ctx, sinceHash)
	ret0, _ := ret[0].([]domain.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitsSince indicates an expected call of CommitsSince.
func (mr *MockGitRepositoryMockRecorder) CommitsSince(ctx, sinceHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitsSince", reflect.TypeOf((*MockGitRepository)(nil).CommitsSince), ctx, sinceHash)
}

// CreateTag mocks base method.
func (m *MockGitRepository) CreateTag(ctx context.Context, name, hash, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, name, hash, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockGitRepositoryMockRecorder) CreateTag(ctx, name, hash, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockGitRepository)(nil).CreateTag), ctx, name, hash, message)
}

// CurrentBranch mocks base method.
func (m *MockGitRepository) CurrentBranch(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBranch", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentBranch indicates an expected call of CurrentBranch.
func (mr *MockGitRepositoryMockRecorder) CurrentBranch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBranch", reflect.TypeOf((*MockGitRepository)(nil).CurrentBranch), ctx)
}

// FilesChangedInCommit mocks base method.
func (m *MockGitRepository) FilesChangedInCommit(ctx context.Context, hash string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesChangedInCommit", ctx, hash)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesChangedInCommit indicates an expected call of FilesChangedInCommit.
func (mr *MockGitRepositoryMockRecorder) FilesChangedInCommit(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesChangedInCommit", reflect.TypeOf((*MockGitRepository)(nil).FilesChangedInCommit), ctx, hash)
}

// HeadHash mocks base method.
func (m *MockGitRepository) HeadHash(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadHash", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadHash indicates an expected call of HeadHash.
func (mr *MockGitRepositoryMockRecorder) HeadHash(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadHash", reflect.TypeOf((*MockGitRepository)(nil).HeadHash), ctx)
}

// ListTags mocks base method.
func (m *MockGitRepository) ListTags(ctx context.Context) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockGitRepositoryMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockGitRepository)(nil).ListTags), ctx)
}

// PushTag mocks base method.
func (m *MockGitRepository) PushTag(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushTag", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushTag indicates an expected call of PushTag.
func (mr *MockGitRepositoryMockRecorder) PushTag(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTag", reflect.TypeOf((*MockGitRepository)(nil).PushTag), ctx, name)
}

// RemoteURL mocks base method.
func (m *MockGitRepository) RemoteURL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteURL indicates an expected call of RemoteURL.
func (mr *MockGitRepositoryMockRecorder) RemoteURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteURL", reflect.TypeOf((*MockGitRepository)(nil).RemoteURL), ctx)
}

// MockCommitParser is a mock of CommitParser interface.
type MockCommitParser struct {
	ctrl     *gomock.Controller
	recorder *MockCommitParserMockRecorder
	isgomock struct{}
}

// MockCommitParserMockRecorder is the mock recorder for MockCommitParser.
type MockCommitParserMockRecorder struct {
	mock *MockCommitParser
}

// NewMockCommitParser creates a new mock instance.
func NewMockCommitParser(ctrl *gomock.Controller) *MockCommitParser {
	mock := &MockCommitParser{ctrl: ctrl}
	mock.recorder = &MockCommitParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommitParser) EXPECT() *MockCommitParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockCommitParser) Parse(message string) (domain.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", message)
	ret0, _ := ret[0].(domain.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCommitParserMockRecorder) Parse(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCommitParser)(nil).Parse), message)
}

// MockProjectDiscoverer is a mock of ProjectDiscoverer interface.
type MockProjectDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockProjectDiscovererMockRecorder
	isgomock struct{}
}

// MockProjectDiscovererMockRecorder is the mock recorder for MockProjectDiscoverer.
type MockProjectDiscovererMockRecorder struct {
	mock *MockProjectDiscoverer
}

// NewMockProjectDiscoverer creates a new mock instance.
func NewMockProjectDiscoverer(ctrl *gomock.Controller) *MockProjectDiscoverer {
	mock := &MockProjectDiscoverer{ctrl: ctrl}
	mock.recorder = &MockProjectDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectDiscoverer) EXPECT() *MockProjectDiscovererMockRecorder {
	return m.recorder
}

// Discover mocks base method.
func (m *MockProjectDiscoverer) Discover(ctx context.Context, rootPath string) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discover", ctx, rootPath)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Discover indicates an expected call of Discover.
func (mr *MockProjectDiscovererMockRecorder) Discover(ctx, rootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discover", reflect.TypeOf((*MockProjectDiscoverer)(nil).Discover), ctx, rootPath)
}

// MockProjectImpactAnalyzer is a mock of ProjectImpactAnalyzer interface.
type MockProjectImpactAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockProjectImpactAnalyzerMockRecorder
	isgomock struct{}
}

// MockProjectImpactAnalyzerMockRecorder is the mock recorder for MockProjectImpactAnalyzer.
type MockProjectImpactAnalyzerMockRecorder struct {
	mock *MockProjectImpactAnalyzer
}

// NewMockProjectImpactAnalyzer creates a new mock instance.
func NewMockProjectImpactAnalyzer(ctrl *gomock.Controller) *MockProjectImpactAnalyzer {
	mock := &MockProjectImpactAnalyzer{ctrl: ctrl}
	mock.recorder = &MockProjectImpactAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectImpactAnalyzer) EXPECT() *MockProjectImpactAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockProjectImpactAnalyzer) Analyze(projects []domain.Project, commits []domain.Commit) map[string][]domain.Commit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", projects, commits)
	ret0, _ := ret[0].(map[string][]domain.Commit)
	return ret0
}

// Analyze indicates an expected call of Analyze.
func (mr *MockProjectImpactAnalyzerMockRecorder) Analyze(projects, commits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockProjectImpactAnalyzer)(nil).Analyze), projects, commits)
}

// MockVersionCalculator is a mock of VersionCalculator interface.
type MockVersionCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockVersionCalculatorMockRecorder
	isgomock struct{}
}

// MockVersionCalculatorMockRecorder is the mock recorder for MockVersionCalculator.
type MockVersionCalculatorMockRecorder struct {
	mock *MockVersionCalculator
}

// NewMockVersionCalculator creates a new mock instance.
func NewMockVersionCalculator(ctrl *gomock.Controller) *MockVersionCalculator {
	mock := &MockVersionCalculator{ctrl: ctrl}
	mock.recorder = &MockVersionCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionCalculator) EXPECT() *MockVersionCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockVersionCalculator) Calculate(current domain.Version, commits []domain.Commit, policy *domain.BranchPolicy, typeMapping map[string]domain.ReleaseType) (domain.Version, domain.ReleaseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", current, commits, policy, typeMapping)
	ret0, _ := ret[0].(domain.Version)
	ret1, _ := ret[1].(domain.ReleaseType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Calculate indicates an expected call of Calculate.
func (mr *MockVersionCalculatorMockRecorder) Calculate(current, commits, policy, typeMapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockVersionCalculator)(nil).Calculate), current, commits, policy, typeMapping)
}

// MockChangelogGenerator is a mock of ChangelogGenerator interface.
type MockChangelogGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockChangelogGeneratorMockRecorder
	isgomock struct{}
}

// MockChangelogGeneratorMockRecorder is the mock recorder for MockChangelogGenerator.
type MockChangelogGeneratorMockRecorder struct {
	mock *MockChangelogGenerator
}

// NewMockChangelogGenerator creates a new mock instance.
func NewMockChangelogGenerator(ctrl *gomock.Controller) *MockChangelogGenerator {
	mock := &MockChangelogGenerator{ctrl: ctrl}
	mock.recorder = &MockChangelogGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangelogGenerator) EXPECT() *MockChangelogGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockChangelogGenerator) Generate(version domain.Version, project string, commits []domain.Commit, sections []domain.ChangelogSectionConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", version, project, commits, sections)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockChangelogGeneratorMockRecorder) Generate(version, project, commits, sections any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockChangelogGenerator)(nil).Generate), version, project, commits, sections)
}

// MockTagService is a mock of TagService interface.
type MockTagService struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceMockRecorder
	isgomock struct{}
}

// MockTagServiceMockRecorder is the mock recorder for MockTagService.
type MockTagServiceMockRecorder struct {
	mock *MockTagService
}

// NewMockTagService creates a new mock instance.
func NewMockTagService(ctrl *gomock.Controller) *MockTagService {
	mock := &MockTagService{ctrl: ctrl}
	mock.recorder = &MockTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagService) EXPECT() *MockTagServiceMockRecorder {
	return m.recorder
}

// FindLatestTag mocks base method.
func (m *MockTagService) FindLatestTag(tags []domain.Tag, project string) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestTag", tags, project)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestTag indicates an expected call of FindLatestTag.
func (mr *MockTagServiceMockRecorder) FindLatestTag(tags, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestTag", reflect.TypeOf((*MockTagService)(nil).FindLatestTag), tags, project)
}

// FormatTag mocks base method.
func (m *MockTagService) FormatTag(project string, version domain.Version) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatTag", project, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FormatTag indicates an expected call of FormatTag.
func (mr *MockTagServiceMockRecorder) FormatTag(project, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatTag", reflect.TypeOf((*MockTagService)(nil).FormatTag), project, version)
}

// ParseTag mocks base method.
func (m *MockTagService) ParseTag(tagName string) (string, domain.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTag", tagName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(domain.Version)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseTag indicates an expected call of ParseTag.
func (mr *MockTagServiceMockRecorder) ParseTag(tagName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTag", reflect.TypeOf((*MockTagService)(nil).ParseTag), tagName)
}

// MockReleasePublisher is a mock of ReleasePublisher interface.
type MockReleasePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockReleasePublisherMockRecorder
	isgomock struct{}
}

// MockReleasePublisherMockRecorder is the mock recorder for MockReleasePublisher.
type MockReleasePublisherMockRecorder struct {
	mock *MockReleasePublisher
}

// NewMockReleasePublisher creates a new mock instance.
func NewMockReleasePublisher(ctrl *gomock.Controller) *MockReleasePublisher {
	mock := &MockReleasePublisher{ctrl: ctrl}
	mock.recorder = &MockReleasePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleasePublisher) EXPECT() *MockReleasePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockReleasePublisher) Publish(ctx context.Context, params ports.PublishParams) (domain.ProjectReleaseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, params)
	ret0, _ := ret[0].(domain.ProjectReleaseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockReleasePublisherMockRecorder) Publish(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockReleasePublisher)(nil).Publish), ctx, params)
}

// MockConfigProvider is a mock of ConfigProvider interface.
type MockConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigProviderMockRecorder
	isgomock struct{}
}

// MockConfigProviderMockRecorder is the mock recorder for MockConfigProvider.
type MockConfigProviderMockRecorder struct {
	mock *MockConfigProvider
}

// NewMockConfigProvider creates a new mock instance.
func NewMockConfigProvider(ctrl *gomock.Controller) *MockConfigProvider {
	mock := &MockConfigProvider{ctrl: ctrl}
	mock.recorder = &MockConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigProvider) EXPECT() *MockConfigProviderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockConfigProvider) Load(path string) (domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigProviderMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigProvider)(nil).Load), path)
}

// MockFileSystem is a mock of FileSystem interface.
type MockFileSystem struct {
	ctrl     *gomock.Controller
	recorder *MockFileSystemMockRecorder
	isgomock struct{}
}

// MockFileSystemMockRecorder is the mock recorder for MockFileSystem.
type MockFileSystemMockRecorder struct {
	mock *MockFileSystem
}

// NewMockFileSystem creates a new mock instance.
func NewMockFileSystem(ctrl *gomock.Controller) *MockFileSystem {
	mock := &MockFileSystem{ctrl: ctrl}
	mock.recorder = &MockFileSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileSystem) EXPECT() *MockFileSystemMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockFileSystem) Exists(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockFileSystemMockRecorder) Exists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFileSystem)(nil).Exists), path)
}

// Glob mocks base method.
func (m *MockFileSystem) Glob(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Glob", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Glob indicates an expected call of Glob.
func (mr *MockFileSystemMockRecorder) Glob(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Glob", reflect.TypeOf((*MockFileSystem)(nil).Glob), pattern)
}

// ReadFile mocks base method.
func (m *MockFileSystem) ReadFile(path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileSystemMockRecorder) ReadFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileSystem)(nil).ReadFile), path)
}

// Walk mocks base method.
func (m *MockFileSystem) Walk(root string, fn fs.WalkDirFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Walk", root, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Walk indicates an expected call of Walk.
func (mr *MockFileSystemMockRecorder) Walk(root, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Walk", reflect.TypeOf((*MockFileSystem)(nil).Walk), root, fn)
}

// WriteFile mocks base method.
func (m *MockFileSystem) WriteFile(path string, data []byte, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFileSystemMockRecorder) WriteFile(path, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFileSystem)(nil).WriteFile), path, data, perm)
}

// MockTemplateRenderer is a mock of TemplateRenderer interface.
type MockTemplateRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRendererMockRecorder
	isgomock struct{}
}

// MockTemplateRendererMockRecorder is the mock recorder for MockTemplateRenderer.
type MockTemplateRendererMockRecorder struct {
	mock *MockTemplateRenderer
}

// NewMockTemplateRenderer creates a new mock instance.
func NewMockTemplateRenderer(ctrl *gomock.Controller) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{ctrl: ctrl}
	mock.recorder = &MockTemplateRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRenderer) EXPECT() *MockTemplateRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockTemplateRenderer) Render(templateStr string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", templateStr, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockTemplateRendererMockRecorder) Render(templateStr, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockTemplateRenderer)(nil).Render), templateStr, data)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPlugin)(nil).Name))
}

// MockVerifyConditionsPlugin is a mock of VerifyConditionsPlugin interface.
type MockVerifyConditionsPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyConditionsPluginMockRecorder
	isgomock struct{}
}

// MockVerifyConditionsPluginMockRecorder is the mock recorder for MockVerifyConditionsPlugin.
type MockVerifyConditionsPluginMockRecorder struct {
	mock *MockVerifyConditionsPlugin
}

// NewMockVerifyConditionsPlugin creates a new mock instance.
func NewMockVerifyConditionsPlugin(ctrl *gomock.Controller) *MockVerifyConditionsPlugin {
	mock := &MockVerifyConditionsPlugin{ctrl: ctrl}
	mock.recorder = &MockVerifyConditionsPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyConditionsPlugin) EXPECT() *MockVerifyConditionsPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockVerifyConditionsPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockVerifyConditionsPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockVerifyConditionsPlugin)(nil).Name))
}

// VerifyConditions mocks base method.
func (m *MockVerifyConditionsPlugin) VerifyConditions(ctx context.Context, rc *domain.ReleaseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyConditions", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyConditions indicates an expected call of VerifyConditions.
func (mr *MockVerifyConditionsPluginMockRecorder) VerifyConditions(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyConditions", reflect.TypeOf((*MockVerifyConditionsPlugin)(nil).VerifyConditions), ctx, rc)
}

// MockAnalyzeCommitsPlugin is a mock of AnalyzeCommitsPlugin interface.
type MockAnalyzeCommitsPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzeCommitsPluginMockRecorder
	isgomock struct{}
}

// MockAnalyzeCommitsPluginMockRecorder is the mock recorder for MockAnalyzeCommitsPlugin.
type MockAnalyzeCommitsPluginMockRecorder struct {
	mock *MockAnalyzeCommitsPlugin
}

// NewMockAnalyzeCommitsPlugin creates a new mock instance.
func NewMockAnalyzeCommitsPlugin(ctrl *gomock.Controller) *MockAnalyzeCommitsPlugin {
	mock := &MockAnalyzeCommitsPlugin{ctrl: ctrl}
	mock.recorder = &MockAnalyzeCommitsPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzeCommitsPlugin) EXPECT() *MockAnalyzeCommitsPluginMockRecorder {
	return m.recorder
}

// AnalyzeCommits mocks base method.
func (m *MockAnalyzeCommitsPlugin) AnalyzeCommits(ctx context.Context, rc *domain.ReleaseContext) (domain.ReleaseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeCommits", ctx, rc)
	ret0, _ := ret[0].(domain.ReleaseType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeCommits indicates an expected call of AnalyzeCommits.
func (mr *MockAnalyzeCommitsPluginMockRecorder) AnalyzeCommits(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeCommits", reflect.TypeOf((*MockAnalyzeCommitsPlugin)(nil).AnalyzeCommits), ctx, rc)
}

// Name mocks base method.
func (m *MockAnalyzeCommitsPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAnalyzeCommitsPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAnalyzeCommitsPlugin)(nil).Name))
}

// MockVerifyReleasePlugin is a mock of VerifyReleasePlugin interface.
type MockVerifyReleasePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyReleasePluginMockRecorder
	isgomock struct{}
}

// MockVerifyReleasePluginMockRecorder is the mock recorder for MockVerifyReleasePlugin.
type MockVerifyReleasePluginMockRecorder struct {
	mock *MockVerifyReleasePlugin
}

// NewMockVerifyReleasePlugin creates a new mock instance.
func NewMockVerifyReleasePlugin(ctrl *gomock.Controller) *MockVerifyReleasePlugin {
	mock := &MockVerifyReleasePlugin{ctrl: ctrl}
	mock.recorder = &MockVerifyReleasePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyReleasePlugin) EXPECT() *MockVerifyReleasePluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockVerifyReleasePlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockVerifyReleasePluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockVerifyReleasePlugin)(nil).Name))
}

// VerifyRelease mocks base method.
func (m *MockVerifyReleasePlugin) VerifyRelease(ctx context.Context, rc *domain.ReleaseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRelease", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyRelease indicates an expected call of VerifyRelease.
func (mr *MockVerifyReleasePluginMockRecorder) VerifyRelease(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRelease", reflect.TypeOf((*MockVerifyReleasePlugin)(nil).VerifyRelease), ctx, rc)
}

// MockGenerateNotesPlugin is a mock of GenerateNotesPlugin interface.
type MockGenerateNotesPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockGenerateNotesPluginMockRecorder
	isgomock struct{}
}

// MockGenerateNotesPluginMockRecorder is the mock recorder for MockGenerateNotesPlugin.
type MockGenerateNotesPluginMockRecorder struct {
	mock *MockGenerateNotesPlugin
}

// NewMockGenerateNotesPlugin creates a new mock instance.
func NewMockGenerateNotesPlugin(ctrl *gomock.Controller) *MockGenerateNotesPlugin {
	mock := &MockGenerateNotesPlugin{ctrl: ctrl}
	mock.recorder = &MockGenerateNotesPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerateNotesPlugin) EXPECT() *MockGenerateNotesPluginMockRecorder {
	return m.recorder
}

// GenerateNotes mocks base method.
func (m *MockGenerateNotesPlugin) GenerateNotes(ctx context.Context, rc *domain.ReleaseContext) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNotes", ctx, rc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNotes indicates an expected call of GenerateNotes.
func (mr *MockGenerateNotesPluginMockRecorder) GenerateNotes(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNotes", reflect.TypeOf((*MockGenerateNotesPlugin)(nil).GenerateNotes), ctx, rc)
}

// Name mocks base method.
func (m *MockGenerateNotesPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockGenerateNotesPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockGenerateNotesPlugin)(nil).Name))
}

// MockPreparePlugin is a mock of PreparePlugin interface.
type MockPreparePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPreparePluginMockRecorder
	isgomock struct{}
}

// MockPreparePluginMockRecorder is the mock recorder for MockPreparePlugin.
type MockPreparePluginMockRecorder struct {
	mock *MockPreparePlugin
}

// NewMockPreparePlugin creates a new mock instance.
func NewMockPreparePlugin(ctrl *gomock.Controller) *MockPreparePlugin {
	mock := &MockPreparePlugin{ctrl: ctrl}
	mock.recorder = &MockPreparePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreparePlugin) EXPECT() *MockPreparePluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPreparePlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPreparePluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPreparePlugin)(nil).Name))
}

// Prepare mocks base method.
func (m *MockPreparePlugin) Prepare(ctx context.Context, rc *domain.ReleaseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockPreparePluginMockRecorder) Prepare(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockPreparePlugin)(nil).Prepare), ctx, rc)
}

// MockPublishPlugin is a mock of PublishPlugin interface.
type MockPublishPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPublishPluginMockRecorder
	isgomock struct{}
}

// MockPublishPluginMockRecorder is the mock recorder for MockPublishPlugin.
type MockPublishPluginMockRecorder struct {
	mock *MockPublishPlugin
}

// NewMockPublishPlugin creates a new mock instance.
func NewMockPublishPlugin(ctrl *gomock.Controller) *MockPublishPlugin {
	mock := &MockPublishPlugin{ctrl: ctrl}
	mock.recorder = &MockPublishPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublishPlugin) EXPECT() *MockPublishPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockPublishPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPublishPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPublishPlugin)(nil).Name))
}

// Publish mocks base method.
func (m *MockPublishPlugin) Publish(ctx context.Context, rc *domain.ReleaseContext) (*domain.ProjectReleaseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, rc)
	ret0, _ := ret[0].(*domain.ProjectReleaseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockPublishPluginMockRecorder) Publish(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublishPlugin)(nil).Publish), ctx, rc)
}

// MockAddChannelPlugin is a mock of AddChannelPlugin interface.
type MockAddChannelPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockAddChannelPluginMockRecorder
	isgomock struct{}
}

// MockAddChannelPluginMockRecorder is the mock recorder for MockAddChannelPlugin.
type MockAddChannelPluginMockRecorder struct {
	mock *MockAddChannelPlugin
}

// NewMockAddChannelPlugin creates a new mock instance.
func NewMockAddChannelPlugin(ctrl *gomock.Controller) *MockAddChannelPlugin {
	mock := &MockAddChannelPlugin{ctrl: ctrl}
	mock.recorder = &MockAddChannelPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddChannelPlugin) EXPECT() *MockAddChannelPluginMockRecorder {
	return m.recorder
}

// AddChannel mocks base method.
func (m *MockAddChannelPlugin) AddChannel(ctx context.Context, rc *domain.ReleaseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChannel", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChannel indicates an expected call of AddChannel.
func (mr *MockAddChannelPluginMockRecorder) AddChannel(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChannel", reflect.TypeOf((*MockAddChannelPlugin)(nil).AddChannel), ctx, rc)
}

// Name mocks base method.
func (m *MockAddChannelPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAddChannelPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAddChannelPlugin)(nil).Name))
}

// MockSuccessPlugin is a mock of SuccessPlugin interface.
type MockSuccessPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockSuccessPluginMockRecorder
	isgomock struct{}
}

// MockSuccessPluginMockRecorder is the mock recorder for MockSuccessPlugin.
type MockSuccessPluginMockRecorder struct {
	mock *MockSuccessPlugin
}

// NewMockSuccessPlugin creates a new mock instance.
func NewMockSuccessPlugin(ctrl *gomock.Controller) *MockSuccessPlugin {
	mock := &MockSuccessPlugin{ctrl: ctrl}
	mock.recorder = &MockSuccessPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccessPlugin) EXPECT() *MockSuccessPluginMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockSuccessPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSuccessPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSuccessPlugin)(nil).Name))
}

// Success mocks base method.
func (m *MockSuccessPlugin) Success(ctx context.Context, rc *domain.ReleaseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Success", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Success indicates an expected call of Success.
func (mr *MockSuccessPluginMockRecorder) Success(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Success", reflect.TypeOf((*MockSuccessPlugin)(nil).Success), ctx, rc)
}

// MockFailPlugin is a mock of FailPlugin interface.
type MockFailPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockFailPluginMockRecorder
	isgomock struct{}
}

// MockFailPluginMockRecorder is the mock recorder for MockFailPlugin.
type MockFailPluginMockRecorder struct {
	mock *MockFailPlugin
}

// NewMockFailPlugin creates a new mock instance.
func NewMockFailPlugin(ctrl *gomock.Controller) *MockFailPlugin {
	mock := &MockFailPlugin{ctrl: ctrl}
	mock.recorder = &MockFailPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailPlugin) EXPECT() *MockFailPluginMockRecorder {
	return m.recorder
}

// Fail mocks base method.
func (m *MockFailPlugin) Fail(ctx context.Context, rc *domain.ReleaseContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fail", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fail indicates an expected call of Fail.
func (mr *MockFailPluginMockRecorder) Fail(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockFailPlugin)(nil).Fail), ctx, rc)
}

// Name mocks base method.
func (m *MockFailPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFailPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFailPlugin)(nil).Name))
}
