package cargo

import "testing"

const workspaceLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "anyhow"
version = "1.0.86"

[[package]]
name = "vcl-core"
version = "0.1.0"
dependencies = [
 "logos",
 "serde",
]

[[package]]
name = "vcl-cli"
version = "0.1.0"
dependencies = [
 "vcl-core",
]
`

func TestUpdateLockVersions(t *testing.T) {
	t.Run("updates only local crates, leaves third-party untouched", func(t *testing.T) {
		got, err := UpdateLockVersions([]byte(workspaceLock), map[string]string{
			"vcl-core": "0.2.0",
			"vcl-cli":  "0.2.0",
		})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "anyhow"
version = "1.0.86"

[[package]]
name = "vcl-core"
version = "0.2.0"
dependencies = [
 "logos",
 "serde",
]

[[package]]
name = "vcl-cli"
version = "0.2.0"
dependencies = [
 "vcl-core",
]
`
		if string(got) != want {
			t.Errorf("got:\n%s\nwant:\n%s", got, want)
		}
	})

	t.Run("single crate", func(t *testing.T) {
		in := `[[package]]
name = "plug-audit"
version = "0.1.0"
`
		got, err := UpdateLockVersions([]byte(in), map[string]string{"plug-audit": "1.0.0"})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := `[[package]]
name = "plug-audit"
version = "1.0.0"
`
		if string(got) != want {
			t.Errorf("got:\n%s\nwant:\n%s", got, want)
		}
	})

	t.Run("does not touch the top-level lockfile format version", func(t *testing.T) {
		in := `version = 4

[[package]]
name = "foo"
version = "0.1.0"
`
		got, err := UpdateLockVersions([]byte(in), map[string]string{"foo": "0.2.0"})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := `version = 4

[[package]]
name = "foo"
version = "0.2.0"
`
		if string(got) != want {
			t.Errorf("got:\n%s\nwant:\n%s", got, want)
		}
	})

	t.Run("name after version within a block", func(t *testing.T) {
		// Cargo emits name before version, but the updater must not depend on order.
		in := `[[package]]
version = "0.1.0"
name = "bar"
`
		got, err := UpdateLockVersions([]byte(in), map[string]string{"bar": "0.3.0"})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := `[[package]]
version = "0.3.0"
name = "bar"
`
		if string(got) != want {
			t.Errorf("got:\n%s\nwant:\n%s", got, want)
		}
	})

	t.Run("no matching crates is a no-op", func(t *testing.T) {
		got, err := UpdateLockVersions([]byte(workspaceLock), map[string]string{"nonexistent": "9.9.9"})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if string(got) != workspaceLock {
			t.Errorf("expected no change, got:\n%s", got)
		}
	})
}
